lane :test do
  android_get_version_name(
    gradle_file: "app/build.gradle" # optional
  )

  android_set_version_name(
    version_name: "1.23.4",
    gradle_file: "app/build.gradle" # optional
  )

  android_get_version_code(
    gradle_file: "app/build.gradle" # optional
  )

  android_set_version_code(
    version_code: 17, # optional, if not specified, Version Code will be incremented
    gradle_file: "app/build.gradle" # optional
  )
end

desc "Submit a new Beta Build to Play Store"
  lane :beta do
    store_password = "test12345"
    key_password = "test12345"
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => key_password,
      }
    )

    upload_to_play_store(
      track: 'internal',
	  release_status: 'draft'
          
       )
end